### DISCUSSION TITLE
Connection timeout

### DISCUSSION THREAD

**Discussion by restlessronin** [vinniefranco/exandra#50] [Q&A] [answered]
First of all, thanks to all the maintainers for creating this library. It looks like it will be really useful.

ATM, I am unable to make the connection to the DB (it seems).

I am running my phoenix app "Mai" in a VS Code dev-container. The docker compose starts scylladb and the app. I can see in the docker explorer that both are running, and I can connect to the ScyllaDB server using DataGrip. So everything is running as it should. I can also ping "scylladb" from the phoenix container.

UPDATE: I had originally forgotten to run `mix ecto.create`. When I tried that, it ran without problems (obviously it could connect to the DB). I can see from DataGrip that the keyspace `mai_chat` has been created successfully.

However, when I try to run `mix ecto.migrate` I still get
```
** (EXIT from #PID<0.99.0>) shutdown: failed to start child: Mai.Repo
    ** (EXIT) :sync_connect_timeout
```
Here is my dev config for exandra (I also tried `contact_points` instead of `nodes`)
config.exs
```elixir
config :mai, Mai.Repo,
  migration_primary_key: [name: :id, type: :binary_id],
  nodes: ["scylladb"],
  keyspace: "mai_chat",
  port: 9042
```
dev.exs
```elixir
config :mai, Mai.Repo,
  sync_connect: 5000,
  log: :info,
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10
```
I am probably missing something incredibly obvious, but I don't know what it is :-)

**Comment by whatyouhide** [comment]
Hi @restlessronin. If you run `iex -S mix` and then

```elixir
iex> {:ok, conn} = Xandra.start_link(nodes: ["scylladb"], keyspace: "mai_chat", sync_connect: 5000)
iex> Xandra.execute(conn, "SELECT * FROM system_info.tables", [])
```

does it connect and execute the query?

**Comment by restlessronin** [comment]
Hi @whatyouhide thanks for responding. No. I'm getting the same error
```
iex -S mix
[notice] Application mai exited: Mai.Application.start(:normal, []) returned an error: shutdown: failed to start child: Mai.Repo
    ** (EXIT) shutdown: failed to start child: Mai.Repo
        ** (EXIT) :sync_connect_timeout
```
which also happens when I do `mix phx.server`

Perhaps `mix ecto.create` isn't starting up the application?

**Reply by whatyouhide** [reply]
Neither of the tasks is, they're both just starting the repo. If you drop and recreate the DB (ecto.drop and ecto.migrate) does it work?

**Reply by restlessronin** [reply]
`mix ecto.drop` runs fine. `mix ecto.migrate` gives the same error, but `mix ecto.create` runs succesfully.

**Comment by restlessronin** [comment]
This is the repo.ex
```elixir
defmodule Mai.Repo do
  use Ecto.Repo,
    otp_app: :mai,
    adapter: Exandra
end
```
and docker-compose entry for scylladb
```
  scylladb:
    image: scylladb/scylla:5.4
    ports:
      - 9042:9042
    command:
      - "--smp"
      - "1"
    healthcheck:
      test: [ "CMD-SHELL", "nodetool -h ::FFFF:127.0.0.1 status" ]
      interval: 20s
      timeout: 10s
      retries: 12
    logging:
      driver: json-file
      options:
        max-size: 50m
```
